<?php

namespace AdminBundle\Repository;

/**
 * colisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class colisRepository extends \Doctrine\ORM\EntityRepository
{
}
