<?php

namespace AppBundle\Repository;

/**
 * hte_mail_stackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_mail_stackRepository extends \Doctrine\ORM\EntityRepository
{
}
