<?php

namespace AppBundle\Repository;

/**
 * hte_back_user_groupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_back_user_groupsRepository extends \Doctrine\ORM\EntityRepository
{
}
