<?php

namespace AdminBundle\Repository;

/**
 * hte_contactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_contactRepository extends \Doctrine\ORM\EntityRepository
{
}
