<?php

namespace AppBundle\Repository;

/**
 * hte_featuresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_featuresRepository extends \Doctrine\ORM\EntityRepository
{
}
