<?php

namespace AppBundle\Repository;

/**
 * hte_bordereau_return_archiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_bordereau_return_archiveRepository extends \Doctrine\ORM\EntityRepository
{
}
