<?php

namespace AdminBundle\Repository;

/**
 * hte_depositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_depositoryRepository extends \Doctrine\ORM\EntityRepository
{
}
