<?php

namespace AppBundle\Repository;

/**
 * hte_expedition_workflowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_expedition_workflowRepository extends \Doctrine\ORM\EntityRepository
{
}
