<?php

namespace AdminBundle\Repository;

/**
 * hte_connexion_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_connexion_userRepository extends \Doctrine\ORM\EntityRepository
{
}
