<?php

namespace AdminBundle\Repository;

/**
 * hte_expedition_packageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_expedition_packageRepository extends \Doctrine\ORM\EntityRepository
{
}
