<?php

namespace AppBundle\Repository;

/**
 * hte_mail_stack_historyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_mail_stack_historyRepository extends \Doctrine\ORM\EntityRepository
{
}
