<?php

namespace AdminBundle\Repository;

/**
 * hte_city_restrictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_city_restrictionRepository extends \Doctrine\ORM\EntityRepository
{
}
