<?php

namespace AppBundle\Repository;

/**
 * hte_pickup_packageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_pickup_packageRepository extends \Doctrine\ORM\EntityRepository
{
}
