<?php

namespace AppBundle\Repository;

/**
 * hte_partnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_partnerRepository extends \Doctrine\ORM\EntityRepository
{
}
