<?php

namespace AdminBundle\Repository;

/**
 * hte_back_user_cityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_back_user_cityRepository extends \Doctrine\ORM\EntityRepository
{
}
