<?php

namespace AppBundle\Repository;

/**
 * hte_package_bordereau_etatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_package_bordereau_etatRepository extends \Doctrine\ORM\EntityRepository
{
}
