<?php

namespace AppBundle\Repository;

/**
 * hte_parameter_valueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_parameter_valueRepository extends \Doctrine\ORM\EntityRepository
{
}
