<?php

namespace AdminBundle\Repository;

/**
 * hte_back_groupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_back_groupsRepository extends \Doctrine\ORM\EntityRepository
{
}
