<?php

namespace AdminBundle\Repository;

/**
 * hte_client_pricingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_client_pricingRepository extends \Doctrine\ORM\EntityRepository
{
}
