<?php

namespace AppBundle\Repository;

/**
 * hte_parameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_parameterRepository extends \Doctrine\ORM\EntityRepository
{
}
