<?php

namespace AdminBundle\Repository;

/**
 * hte_clientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_clientRepository extends \Doctrine\ORM\EntityRepository
{
}
