<?php

namespace AppBundle\Repository;

/**
 * hte_package_archiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_package_archiveRepository extends \Doctrine\ORM\EntityRepository
{
}
