<?php

namespace AppBundle\Repository;

/**
 * hte_city_restriction_backRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_city_restriction_backRepository extends \Doctrine\ORM\EntityRepository
{
}
