<?php

namespace AdminBundle\Repository;

/**
 * hte_addressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hte_addressRepository extends \Doctrine\ORM\EntityRepository
{
}
